###########################################################################
# Makefile
# The Makefile of vk.hardware/arm/cortex-m/hal
#
# $Copyright: Copyright (C) village
############################################################################

ifeq ($(CONFIG_STM32F4xx), y)
-include vk.hardware/arm/cortex-m/hal/st/stm32f4xx/Makefile
endif

ifeq ($(CONFIG_STM32H7xx), y)
-include vk.hardware/arm/cortex-m/hal/st/stm32h7xx/Makefile
endif
