###########################################################################
# Makefile
# The Makefile of vklibc++
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# paths
######################################
inc-$(CONFIG_VKLIBC)                 += vk.kernel/libraries/vklibc++/inc

src-$(CONFIG_VKLIBC)                 += vk.kernel/libraries/vklibc++/src


######################################
# objects
######################################
objs-$(CONFIG_VKLIBC)                += icxxabi.o
