###########################################################################
# Makefile
# The Makefile of legacy
#
# $Copyright: Copyright (C) village
############################################################################

ifeq ($(CONFIG_IA32), y)
include $(WORKSPACE)/village-boot/legacy/ia32bios/Makefile
endif
