###########################################################################
# Makefile
# The Makefile of village-kernel/stdlib
#
# $Copyright: Copyright (C) village
############################################################################

ifeq ($(CONFIG_VKLIBC), y)
-include village-kernel/stdlib/libm/Makefile
-include village-kernel/stdlib/libc++/Makefile
-include village-kernel/stdlib/libc/Makefile
endif
