###########################################################################
# Makefile
# The Makefile of desktop
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# applications
######################################
apps-$(CONFIG_DESKTOP)                += desktop


######################################
# paths
######################################
inc-desktop-$(CONFIG_DESKTOP)          += village-os/applications/desktop/inc

src-desktop-$(CONFIG_DESKTOP)          += village-os/applications/desktop/src


######################################
# objects
######################################
objs-desktop-$(CONFIG_DESKTOP)         += Desktop.o


######################################
# libraries
######################################
libs-desktop-$(CONFIG_DESKTOP)         += vkgui utils stdc++ c
