###########################################################################
# Makefile
# The Makefile of desktop
#
# $Copyright: Copyright (C) village
############################################################################
ifeq ($(CONFIG_DESKTOP), y)

######################################
# applications
######################################
apps-y                                += desktop


######################################
# paths
######################################
inc-desktop-y                         += village-os/applications/desktop/inc
src-desktop-y                         += village-os/applications/desktop/src


######################################
# objects
######################################
objs-desktop-y                        += Desktop.o


######################################
# libraries
######################################
libs-desktop-y                        += vkgui utils stdc++ c

endif
