###########################################################################
# Makefile
# The Makefile of vk.hardware/HAL
#
# $Copyright: Copyright (C) village
############################################################################

ifeq ($(CONFIG_STM32F4xx), y)
-include vk.hardware/HAL/ST/STM32F4xx/Makefile
endif
