######################################
# paths
######################################
inc-$(CONFIG_STM32H7xx) += vk.hardware/arm/cortex-m/hal/st/stm32h7xx/inc
src-$(CONFIG_STM32H7xx) += vk.hardware/arm/cortex-m/hal/st/stm32h7xx/src


######################################
# objects
######################################
objs-$(CONFIG_HAL_GPIO)   += Gpio.o
objs-$(CONFIG_HAL_GPI)    += Gpi.o
objs-$(CONFIG_HAL_GPO)    += Gpo.o
objs-$(CONFIG_HAL_NVIC)   += Nvic.o
objs-$(CONFIG_HAL_USART)  += Usart.o
objs-$(CONFIG_HAL_SPI)    += Spi.o
objs-$(CONFIG_HAL_I2C)    += I2c.o
objs-$(CONFIG_HAL_DMA)    += Dma.o
objs-$(CONFIG_HAL_FSMC)   += Fsmc.o
