###########################################################################
# Makefile
# The Makefile of fatfs
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# paths
######################################
inc-$(CONFIG_FATFS)                  += vk.kernel/libraries/fatfs/inc

src-$(CONFIG_FATFS)                  += vk.kernel/libraries/fatfs/src


######################################
# objects
######################################
objs-$(CONFIG_FATFS)                 += diskio.o
objs-$(CONFIG_FATFS)                 += ff.o
objs-$(CONFIG_FATFS)                 += ffsystem.o
objs-$(CONFIG_FATFS)                 += ffunicode.o
