###########################################################################
# Makefile
# The Makefile of settings
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# applications
######################################
apps-$(CONFIG_SETTINGS)              += settings


######################################
# paths
######################################
inc-settings-$(CONFIG_SETTINGS)      += vk.application/settings/inc

src-settings-$(CONFIG_SETTINGS)      += vk.application/settings/src


######################################
# objects
######################################
objs-settings-$(CONFIG_SETTINGS)     += Settings.o


######################################
# libraries
######################################
libs-settings-$(CONFIG_SETTINGS)     += kernel gui
