###########################################################################
# Makefile
# The Makefile of vk.hardware/arm/
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# paths
######################################
inc-y += vk.hardware/arm/cortex-m/driver/config
inc-y += vk.hardware/arm/cortex-m/driver/inc
src-y += vk.hardware/arm/cortex-m/driver/src

######################################
# objects
######################################
objs-$(CONFIG_DMAFIFO)        += DmaFifo.o
objs-$(CONFIG_ILI9488)        += ILI9488.o
objs-$(CONFIG_SDCARD)         += SdCard.o
objs-$(CONFIG_SPIFLASH)       += SpiFlash.o
objs-$(CONFIG_UARTSERIAL)     += UartSerial.o
objs-$(CONFIG_USBSTORAGE)     += UsbStorage.o
