###########################################################################
# Makefile
# The Makefile of vk.hardware/x86/bios/hal
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# paths
######################################
inc-y                                   += vk.hardware/x86/bios/hal/inc
src-y                                   += vk.hardware/x86/bios/hal/src


######################################
# objects
######################################
objs-hw-$(CONFIG_HAL_PCI_CONTROLLER)     += PCIController.o
objs-hw-$(CONFIG_HAL_PS2_CONTROLLER)     += PS2Controller.o
