###########################################################################
# Makefile
# The Makefile of demo
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# paths
######################################
inc-$(CONFIG_DEMO_MOD)                 += village-demo/modules/demo/inc
src-$(CONFIG_DEMO_MOD)                 += village-demo/modules/demo/src


######################################
# objects
######################################
objs-$(CONFIG_DEMO_MOD)                += demo_mod.o
