###########################################################################
# Makefile
# The Makefile of village-demo
#
# $Copyright: Copyright (C) village
############################################################################

# libraries
include village-demo/libraries/crt0/Makefile

# programs
include village-demo/programs/demo/Makefile

# services
include village-demo/services/taichi/Makefile
