###########################################################################
# Makefile
# The Makefile of VK.Application
#
# $Copyright: Copyright (C) jingwei
############################################################################

######################################
# includes
######################################
INCLUDES += 


######################################
# sources
######################################
# ASM sources
ASM_SOURCES +=

# C sources
C_SOURCES += 

# Cpp sources
CPP_SOURCES += VK.Application/Start.cpp

