###########################################################################
# Makefile
# The Makefile of vk.aplication
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# includes
######################################
INCLUDES += -I./vk.application/hardware/config \
	-I./vk.application/hardware/inc \
	-I./vk.application/application/inc


######################################
# sources
######################################
# ASM sources
ASM_SOURCES +=

# C sources
C_SOURCES += 

# Cpp sources
CPP_SOURCES += vk.application/Start.cpp \
	vk.application/hardware/src/HWManager.cpp \
	vk.application/application/src/Application1.cpp \
	vk.application/application/src/Application2.cpp \
	vk.application/application/src/Application3.cpp

