###########################################################################
# Makefile
# The Makefile of VK.Application
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# includes
######################################
INCLUDES += -I./VK.Application/application/inc


######################################
# sources
######################################
# ASM sources
ASM_SOURCES +=

# C sources
C_SOURCES += 

# Cpp sources
CPP_SOURCES += VK.Application/Start.cpp \
	VK.Application/application/src/Application.cpp

