###########################################################################
# Makefile
# The Makefile of vk.hardware/DEV
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# paths
######################################
inc-y += vk.hardware/DEV/x86/inc
src-y += vk.hardware/DEV/x86/src

######################################
# objects
######################################
objs-$(CONFIG_UARTSERIAL)  += UartSerial.o
objs-$(CONFIG_VGA)         += VGA.o
