######################################
# paths
######################################
inc-$(CONFIG_X86) += vk.hardware/HAL/x86/inc
src-$(CONFIG_X86) += vk.hardware/HAL/x86/src


######################################
# objects
######################################
objs-$(CONFIG_HAL_SYSTEM) += System.o
objs-$(CONFIG_HAL_GPIO)   += Gpio.o
objs-$(CONFIG_HAL_GPI)    += Gpi.o
objs-$(CONFIG_HAL_GPO)    += Gpo.o
objs-$(CONFIG_HAL_USART)  += Usart.o
