######################################
# paths
######################################
inc-$(CONFIG_X86) += vk.hardware/HAL/x86/inc
src-$(CONFIG_X86) += vk.hardware/HAL/x86/src


######################################
# objects
######################################
objs-$(CONFIG_HAL_SYSTEM) += System.o
