###########################################################################
# Makefile
# The Makefile of village-kernel/drivers/x86/bios
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# paths
######################################
inc-y                                 += village-kernel/drivers/x86/bios/inc
src-y                                 += village-kernel/drivers/x86/bios/src

######################################
# objects
######################################
objs-$(CONFIG_ATALBADISK)             += AtaLbaDisk.o
objs-$(CONFIG_BOCHSVBE)               += BochsVBE.o
objs-$(CONFIG_GENERALTIMER)           += GeneralTimer.o
objs-$(CONFIG_PS2KEYBOARD)            += PS2KeyBoard.o
objs-$(CONFIG_PS2MOUSE)               += PS2Mouse.o
objs-$(CONFIG_SERIALPORT)             += SerialPort.o
