###########################################################################
# Makefile
# The Makefile of vk.hardware/x86/bios
#
# $Copyright: Copyright (C) village
############################################################################

-include vk.hardware/x86/bios/cpu/Makefile
-include vk.hardware/x86/bios/driver/Makefile
