/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>


/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void)   __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
__attribute__((weak)) void initialise_monitor_handles()
{
}

__attribute__((weak)) int _getpid(void)
{
	return 1;
}

__attribute__((weak)) int _kill(int pid, int sig)
{
	errno = EINVAL;
	return -1;
}

__attribute__((weak)) void _exit (int status)
{
	_kill(status, -1);
	while (1) {}		/* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
	for (int index = 0; index < len; index++)
	{
		*ptr++ = __io_getchar();
	}
	return len;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
	for (int index = 0; index < len; index++)
	{
		__io_putchar(*ptr++);
	}
	return len;
}

__attribute__((weak)) int _close(int file)
{
	return -1;
}

__attribute__((weak)) int _fstat(int file, struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

__attribute__((weak)) int _isatty(int file)
{
	return 1;
}

__attribute__((weak)) int _lseek(int file, int ptr, int dir)
{
	return 0;
}

__attribute__((weak)) int _open(char *path, int flags, ...)
{
	/* Pretend like we always fail */
	return -1;
}

__attribute__((weak)) int _wait(int *status)
{
	errno = ECHILD;
	return -1;
}

__attribute__((weak)) int _unlink(char *name)
{
	errno = ENOENT;
	return -1;
}

__attribute__((weak)) int _times(struct tms *buf)
{
	return -1;
}

__attribute__((weak)) int _stat(char *file, struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

__attribute__((weak)) int _link(char *old, char *new)
{
	errno = EMLINK;
	return -1;
}

__attribute__((weak)) int _fork(void)
{
	errno = EAGAIN;
	return -1;
}

__attribute__((weak)) int _execve(char *name, char **argv, char **env)
{
	errno = ENOMEM;
	return -1;
}
