###########################################################################
# Makefile
# The Makefile of vk.hardware/DEV
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# paths
######################################
inc-y                            += vk.hardware/x86/bios/driver/inc
src-y                            += vk.hardware/x86/bios/driver/src

######################################
# objects
######################################
objs-$(CONFIG_ATALBADISK)        += AtaLbaDisk.o
objs-$(CONFIG_BOCHSVBE)          += BochsVBE.o
objs-$(CONFIG_GENERALTIMER)      += GeneralTimer.o
objs-$(CONFIG_PS2KEYBOARD)       += PS2KeyBoard.o
objs-$(CONFIG_PS2MOUSE)          += PS2Mouse.o
objs-$(CONFIG_SERIALPORT)        += SerialPort.o
