###########################################################################
# Makefile
# The Makefile of vk.hardware/DEV
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# paths
######################################
inc-y += vk.hardware/x86/bios/driver/inc
src-y += vk.hardware/x86/bios/driver/src

######################################
# objects
######################################
objs-$(CONFIG_SERIAL)         += Serial.o
objs-$(CONFIG_BOCHSVBE)       += BochsVBE.o
objs-$(CONFIG_VGA)            += VGA.o
objs-$(CONFIG_DISK)           += Disk.o
objs-$(CONFIG_PS2KEYBOARD)    += PS2KeyBoard.o
objs-$(CONFIG_PS2MOUSE)       += PS2Mouse.o
