###########################################################################
# Makefile
# The Makefile of settings
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# applications
######################################
apps-$(CONFIG_TAICHI)                += taichi


######################################
# paths
######################################
inc-taichi-$(CONFIG_TAICHI)          += village-os/applications/taichi/inc

src-taichi-$(CONFIG_TAICHI)          += village-os/applications/taichi/src


######################################
# objects
######################################
objs-taichi-$(CONFIG_TAICHI)         += Taichi.o


######################################
# libraries
######################################
libs-taichi-$(CONFIG_TAICHI)         += utils stdc++ c
