###########################################################################
# Makefile
# The Makefile of settings
#
# $Copyright: Copyright (C) village
############################################################################
ifeq ($(CONFIG_TAICHI), y)

######################################
# applications
######################################
apps-y                                += taichi


######################################
# paths
######################################
inc-taichi-y                          += village-os/applications/taichi/inc
src-taichi-y                          += village-os/applications/taichi/src


######################################
# objects
######################################
objs-taichi-y                         += Taichi.o


######################################
# libraries
######################################
libs-taichi-y                         += utils stdc++ c

endif
