###########################################################################
# Makefile
# The Makefile of aplications
#
# $Copyright: Copyright (C) village
############################################################################

-include village-os/applications/taichi/Makefile
-include village-os/applications/console/Makefile
-include village-os/applications/desktop/Makefile
-include village-os/applications/settings/Makefile
