###########################################################################
# Makefile
# The Makefile of simple input
#
# $Copyright: Copyright (C) village
############################################################################
ifeq ($(CONFIG_SIMPLE_INPUT_APP), y)

######################################
# applications
######################################
apps-y                                += simpleInput


######################################
# paths
######################################
inc-simpleInput-y                     += village-os/applications/simpleInput/inc
src-simpleInput-y                     += village-os/applications/simpleInput/src


######################################
# objects
######################################
objs-simpleInput-y                    += SimpleInput.o


######################################
# libraries
######################################
libs-simpleInput-y                    += utils c

endif
