###########################################################################
# Makefile
# The Makefile of simple input
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# applications
######################################
apps-$(CONFIG_SIMPLE_INPUT)               += simpleInput


######################################
# paths
######################################
inc-simpleInput-$(CONFIG_SIMPLE_INPUT)   += village-os/applications/simpleInput/inc

src-simpleInput-$(CONFIG_SIMPLE_INPUT)   += village-os/applications/simpleInput/src


######################################
# objects
######################################
objs-simpleInput-$(CONFIG_SIMPLE_INPUT)  += SimpleInput.o


######################################
# libraries
######################################
libs-simpleInput-$(CONFIG_SIMPLE_INPUT)  += utils
