################GenKconfig.py###################
# this program generate kconfig and makefile file
################################################# 
import sys
import os

if len(sys.argv) < 2:
	print ('Invalid format')
	print ('Usage: %s [srcpath]' % (os.path.basename(sys.argv[0])))
	sys.exit()
else:
    srcpath = sys.argv[1]
    makefile = "Makefile_gen"
    kconfig  = "Kconfig_gen"

# get the name of source files and generated makefile content
makefileText = "## This file is generated by vk.scripts/GenKconfig.py ##\n"
kconfigText  = makefileText
for file in os.listdir(srcpath):
    if file.endswith(".c") or file.endswith(".cpp"):
        config  = str(file).replace(".cpp", '').replace(".c", '').upper()
        objname = str(file).replace('.c','.o')
        makefileText += ("objs-$(CONFIG_%s) %35s\n") % (config, "+= " + objname)
        kconfigText  += ("config %s\n\tbool \"build %s\"\n\tdefault n\n\n") % (config, file)
        
# save content to file
Makefile = open(makefile, mode="w", newline="\r\n")
Makefile.write(makefileText)
Makefile.close()

# save kconfig content to file
Kconfig = open(kconfig, mode="w", newline="\n")
Kconfig.write(kconfigText)
Kconfig.close()
