###########################################################################
# Makefile
# The Makefile of village-kernel/vklibs/libhw/arm/cortex-m
#
# $Copyright: Copyright (C) village
############################################################################

ifeq ($(CONFIG_ST), y)
-include village-kernel/vklibs/libhw/arm/cortex-m/hal/st/Makefile
-include village-kernel/vklibs/libhw/arm/cortex-m/mcu/st/Makefile
endif
