###########################################################################
# Makefile
# The Makefile of vk.hardware/arm/cortex-m
#
# $Copyright: Copyright (C) village
############################################################################

-include vk.hardware/arm/cortex-m/driver/Makefile

ifeq ($(CONFIG_ST), y)
-include vk.hardware/arm/cortex-m/hal/st/Makefile
-include vk.hardware/arm/cortex-m/mcu/st/Makefile
endif
