###########################################################################
# Makefile
# The Makefile of vk.hardware/x86
#
# $Copyright: Copyright (C) village
############################################################################

ifeq ($(CONFIG_BIOS), y)
-include vk.hardware/x86/bios/Makefile
endif

ifeq ($(CONFIG_UEFI), y)
-include vk.hardware/x86/uefi/Makefile
endif
