###########################################################################
# Makefile
# The Makefile of vk.hardware/BSP
#
# $Copyright: Copyright (C) village
############################################################################

ifeq ($(CONFIG_ST), y)
-include vk.hardware/BSP/ST/Makefile
endif
