###########################################################################
# Makefile
# The Makefile of vk.hardware
#
# $Copyright: Copyright (C) village
############################################################################

ifeq ($(CONFIG_ARM), y)
-include vk.hardware/arm/Makefile
endif

ifeq ($(CONFIG_X86), y)
-include vk.hardware/x86/Makefile
endif
