###########################################################################
# Makefile
# The Makefile of vk.hardware
#
# $Copyright: Copyright (C) village
############################################################################

ifeq ($(CONFIG_CORTEX_M), y)
-include vk.hardware/arm/cortex-m/Makefile
endif
