###########################################################################
# Makefile
# The Makefile of launch
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# applications
######################################
apps-$(CONFIG_LAUNCH)                += launch


######################################
# paths
######################################
inc-launch-$(CONFIG_LAUNCH)          += village-os/applications/launch/inc

src-launch-$(CONFIG_LAUNCH)          += village-os/applications/launch/src


######################################
# objects
######################################
objs-launch-$(CONFIG_LAUNCH)         += Launch.o


######################################
# libraries
######################################
libs-launch-$(CONFIG_LAUNCH)         += vkgui kernel stdc++ c
