###########################################################################
# Makefile
# The Makefile of demo
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# applications
######################################
apps-$(CONFIG_DEMO)                  += 


######################################
# paths
######################################
inc-$(CONFIG_DEMO)                   += vk.application/demo/inc

src-$(CONFIG_DEMO)                   += vk.application/demo/src


######################################
# objects
######################################
objs-$(CONFIG_APPLICATION1)          += Application1.o
objs-$(CONFIG_APPLICATION2)          += Application2.o
objs-$(CONFIG_APPLICATION3)          += Application3.o
objs-$(CONFIG_APPLICATION4)          += Application4.o
objs-$(CONFIG_APPLICATION5)          += Application5.o
objs-$(CONFIG_APPLICATION6)          += Application6.o


######################################
# libraries
######################################
libs-demo-$(CONFIG_APPLICATION6)     += 
