###########################################################################
# Makefile
# The Makefile of launch
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# applications
######################################
apps-$(CONFIG_LAUNCH)                += launch


######################################
# paths
######################################
inc-$(CONFIG_LAUNCH)                 += vk.application/launch/inc

src-$(CONFIG_LAUNCH)                 += vk.application/launch/src


######################################
# objects
######################################
objs-launch-$(CONFIG_LAUNCH)         += Launch.o


######################################
# libraries
######################################
libs-launch-$(CONFIG_LAUNCH)         += kernel graphics
