###########################################################################
# Makefile
# The Makefile of vk.hardware/x86
#
# $Copyright: Copyright (C) village
############################################################################

-include vk.hardware/x86/cpu/Makefile
-include vk.hardware/x86/driver/Makefile
