###########################################################################
# Makefile
# The Makefile of village-os
#
# $Copyright: Copyright (C) village
############################################################################

# includes
-include village-os/applications/Makefile
-include village-os/framework/crt0/Makefile
-include village-os/framework/vkgui/Makefile
