###########################################################################
# Makefile
# The Makefile of village-os
#
# $Copyright: Copyright (C) village
############################################################################

# libraries
include village-os/libraries/crt0/Makefile

# programs
include village-os/programs/desktop/Makefile
include village-os/programs/settings/Makefile
include village-os/programs/terminal/Makefile

# services
include village-os/services/taichi/Makefile
include village-os/services/input/Makefile
include village-os/services/vkgui/Makefile
