###########################################################################
# Makefile
# The Makefile of settings
#
# $Copyright: Copyright (C) village
############################################################################
ifeq ($(CONFIG_SETTINGS), y)

######################################
# applications
######################################
apps-y                                += settings


######################################
# paths
######################################
inc-settings-y                        += village-os/applications/settings/inc
src-settings-y                        += village-os/applications/settings/src


######################################
# objects
######################################
objs-settings-y                       += Settings.o


######################################
# libraries
######################################
libs-settings-y                       += utils gui

endif
