###########################################################################
# Makefile
# The Makefile of input
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# applications
######################################
apps-$(CONFIG_INPUT)               += input


######################################
# paths
######################################
inc-input-$(CONFIG_INPUT)          += village-os/applications/input/inc

src-input-$(CONFIG_INPUT)          += village-os/applications/input/src


######################################
# objects
######################################
objs-input-$(CONFIG_INPUT)         += Input.o


######################################
# libraries
######################################
libs-input-$(CONFIG_INPUT)         += kernel
