###########################################################################
# Makefile
# The Makefile of vk.hardware/DEV
#
# $Copyright: Copyright (C) village
############################################################################

######################################
# paths
######################################
inc-y += vk.hardware/x86/driver/inc
src-y += vk.hardware/x86/driver/src

######################################
# objects
######################################
objs-hw-$(CONFIG_SERIAL)      += Serial.o
objs-hw-$(CONFIG_VGA)         += VGA.o
objs-hw-$(CONFIG_VGA)         += Disk.o
